spring:
  profiles:
    active: dev
  servlet:
    encoding:
      charset: UTF-8
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  jpa:
    hibernate:
      order_inserts: true
      order_updates: true
      ddl-auto: none
      use-new-id-generator-mapping: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: false
    show-sql: true
    database: mysql
    properties:
      hibernate:
        jdbc:
          batch_size: 20
        order_inserts: true
        format_sql: true
        enable_lazy_load_no_trans: true
        globally_quoted_identifiers: true
        default_batch_fetch_size: 1000

server:
  servlet:
    context-path: /demo
---
spring:
  config:
    activate:
      on-profile: prod
  servlet:
    multipart:
      location: /mnt/data/temp/
  datasource:
    hikari:
      platform: mysql
      jdbc-url: jdbc:mysql://127.0.0.1:3300/TEST_DB?useSSL=false&characterEncoding=UTF-8
      username: root
      password: mariadb
      driver-class-name: com.mysql.cj.jdbc.Driver
      pool-name: db-pool
      connection-timeout: 30000
      minimum-idle: 10
      maximum-pool-size: 30
      idle-timeout: 600000
      validation-timeout: 5000
      max-lifetime: 1800000
      auto-commit: false
server:
  port: 9090
logging:
  config: classpath:logback/logback-spring-prod.xml
---
spring:
  config:
    activate:
      on-profile: dev
  servlet:
    multipart:
      location: D:/data/temp/
  datasource:
    hikari:
      platform: mysql
      jdbc-url: jdbc:mysql://127.0.0.1:3300/TEST_DB?useSSL=false&characterEncoding=UTF-8
      username: root
      password: mariadb
      driver-class-name: com.mysql.cj.jdbc.Driver
      pool-name: db-pool
      connection-timeout: 30000
      minimum-idle: 10
      maximum-pool-size: 30
      idle-timeout: 600000
      validation-timeout: 5000
      max-lifetime: 1800000
      auto-commit: false
server:
  port: 9999
logging:
  config: classpath:logback/logback-spring-dev.xml
