spring:
  profiles:
    active: dev
  servlet:
    encoding:
      charset: UTF-8
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  jpa:
    hibernate:
      order_inserts: true
      order_updates: true
      ddl-auto: none
      use-new-id-generator-mapping: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: false
    show-sql: true
    database: mysql
    properties:
      hibernate:
        jdbc:
          batch_size: 20
        order_inserts: true
        format_sql: true
        enable_lazy_load_no_trans: true
        globally_quoted_identifiers: true
        default_batch_fetch_size: 1000

server:
  servlet:
    context-path: /chat
---
spring:
  config:
    activate:
      on-profile: prod
  servlet:
    multipart:
      location: /usr/data/temp/
server:
  port: 9090
logging:
  config: classpath:logback/logback-spring-prod.xml
---
spring:
  config:
    activate:
      on-profile: dev
  servlet:
    multipart:
      location: D:/data/temp/
server:
  port: 9999
logging:
  config: classpath:logback/logback-spring-dev.xml
